/*
 * This file is part of Jpsonic.
 *
 * Jpsonic is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Jpsonic is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * (C) 2026 tesshucom
 */

package com.tesshu.jpsonic.service.settings;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;

import com.tesshu.jpsonic.infrastructure.EnvironmentProvider;
import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.FileBasedConfiguration;
import org.apache.commons.configuration2.PropertiesConfiguration;
import org.apache.commons.configuration2.PropertiesConfigurationLayout;
import org.apache.commons.configuration2.builder.BuilderParameters;
import org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder;
import org.apache.commons.configuration2.builder.fluent.Parameters;
import org.apache.commons.configuration2.ex.ConfigurationException;
import org.apache.commons.configuration2.sync.ReadWriteSynchronizer;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.exception.UncheckedException;
import org.springframework.context.annotation.Bean;

@org.springframework.context.annotation.Configuration
public class SettingsConfiguration {

    @Bean
    public FileBasedConfigurationBuilder<FileBasedConfiguration> settingsBuilder() {
        Path propertyFile = EnvironmentProvider.getInstance().getPropertyFilePath();

        if (!Files.exists(propertyFile)) {
            try {
                FileUtils.touch(propertyFile.toFile());
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        }

        PropertiesConfigurationLayout layout = new PropertiesConfigurationLayout();
        layout.setHeaderComment("""
                Jpsonic preferences. NOTE: This file is automatically generated.
                Do not modify while application is running
                """);
        layout.setGlobalSeparator("=");

        BuilderParameters params = new Parameters()
            .properties()
            .setFile(propertyFile.toFile())
            .setSynchronizer(new ReadWriteSynchronizer())
            .setLayout(layout);

        return new FileBasedConfigurationBuilder<FileBasedConfiguration>(
                PropertiesConfiguration.class)
            .configure(params);
    }

    @Bean
    public Configuration settingsConfig(
            FileBasedConfigurationBuilder<FileBasedConfiguration> builder) {
        try {
            return builder.getConfiguration();
        } catch (ConfigurationException e) {
            throw new UncheckedException(e);
        }
    }
}
