/*
 * This file is part of Jpsonic.
 *
 * Jpsonic is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Jpsonic is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * (C) 2026 tesshucom
 */

package com.tesshu.jpsonic.infrastructure.settings;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.CompletionException;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import com.tesshu.jpsonic.infrastructure.core.EnvironmentProvider;
import com.tesshu.jpsonic.infrastructure.db.DataSourceConfigType;
import com.tesshu.jpsonic.infrastructure.filesystem.FileOperations;
import com.tesshu.jpsonic.util.LegacyMap;
import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.FileBasedConfiguration;
import org.apache.commons.configuration2.ImmutableConfiguration;
import org.apache.commons.configuration2.MapConfiguration;
import org.apache.commons.configuration2.PropertiesConfiguration;
import org.apache.commons.configuration2.PropertiesConfigurationLayout;
import org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder;
import org.apache.commons.configuration2.builder.fluent.Parameters;
import org.apache.commons.configuration2.ex.ConfigurationException;
import org.apache.commons.configuration2.sync.ReadWriteSynchronizer;
import org.apache.commons.lang3.StringUtils;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.PropertySource;
import org.springframework.stereotype.Component;
import org.springframework.web.context.ConfigurableWebApplicationContext;

/**
 * Initializer that loads jpsonic.properties and activates the database profile
 * before the Spring ApplicationContext is refreshed.
 * 
 * <p>
 * This class consolidates the physical loading logic (formerly
 * ApacheCommonsConfigurationService), the Spring Environment adapter (formerly
 * CommonsConfigurationPropertySource), and the profile activation logic
 * (formerly CustomPropertySourceConfigurer).
 * </p>
 */
@Component
class PropertySourceInitializer
        implements ApplicationContextInitializer<ConfigurableWebApplicationContext> {

    private static final Logger LOG = LoggerFactory.getLogger(PropertySourceInitializer.class);
    private static final String DATASOURCE_CONFIG_TYPE = "DatabaseConfigType";
    private static final String HEADER_COMMENT = """
            Jpsonic preferences.  NOTE: This file is automatically generated.\
             Do not modify while application is running\
            """;

    @Override
    public void initialize(ConfigurableWebApplicationContext ctx) {
        LOG.info("Initializing Jpsonic PropertySource...");

        // 1. Physical Load using Apache Commons Configuration logic
        ImmutableConfiguration snapshot = loadPhysicalConfiguration();

        // 2. Activate Database Profile based on the loaded properties
        activateDatabaseProfile(ctx.getEnvironment(), snapshot);

        // 3. Wrap and register as a Spring PropertySource
        ctx
            .getEnvironment()
            .getPropertySources()
            .addLast(new ConfigurationAdapter("jpsonic-pre-init-configs", snapshot));
    }

    private ImmutableConfiguration loadPhysicalConfiguration() {
        Path propertyFile = EnvironmentProvider.getInstance().getPropertyFilePath();

        // Ensure the file exists (using our new FileOperations!)
        if (!Files.exists(propertyFile)) {
            try {
                FileOperations.touch(propertyFile);
            } catch (IOException e) {
                throw new CompletionException("Could not create new property file", e);
            }
        }

        PropertiesConfigurationLayout layout = new PropertiesConfigurationLayout();
        layout.setHeaderComment(HEADER_COMMENT);
        layout.setGlobalSeparator("=");

        Parameters params = new Parameters();
        FileBasedConfigurationBuilder<FileBasedConfiguration> builder = new FileBasedConfigurationBuilder<FileBasedConfiguration>(
                PropertiesConfiguration.class)
            .configure(params
                .properties()
                .setFile(propertyFile.toFile())
                .setSynchronizer(new ReadWriteSynchronizer())
                .setLayout(layout));

        try {
            // Do not allow line breaks
            Configuration config = builder.getConfiguration();
            config.getKeys().forEachRemaining(key -> {
                layout.setBlankLinesBefore(key, 0);
            });

            MapConfiguration snapshot = new MapConfiguration(LegacyMap.of());
            snapshot.copy(config);
            return snapshot;
        } catch (ConfigurationException e) {
            throw new CompletionException("Could not load property file at " + propertyFile, e);
        }
    }

    private void activateDatabaseProfile(ConfigurableEnvironment env,
            ImmutableConfiguration config) {
        String rawType = config.getString(DATASOURCE_CONFIG_TYPE, "H2");
        String profile = StringUtils.lowerCase(DataSourceConfigType.of(rawType).name());
        List<String> profiles = Stream.of(env.getActiveProfiles()).collect(Collectors.toList());
        if (!profiles.contains(profile)) {
            profiles.add(profile);
            env.setActiveProfiles(profiles.toArray(new String[0]));
            LOG.info("Activated database profile: {}", profile);
        }
    }

    /**
     * Internal adapter to bridge Apache Commons Configuration and Spring
     * PropertySource.
     */
    private static class ConfigurationAdapter extends PropertySource<ImmutableConfiguration> {
        ConfigurationAdapter(String name, ImmutableConfiguration source) {
            super(name, source);
        }

        @Override
        public Object getProperty(@NonNull String name) {
            return source.getProperty(name);
        }
    }
}
