# Configuration for Dependabot - https://dependabot.com/docs/config-file/

version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    target_branch: "snapshot-109.0.0"
    default_labels:
      - "type: dependency-upgrade"
