# Currently Windows only validates Java LTS version
# Send the coverage of Java LTS version on Linux to Cadacy
name: CI
on:
  push:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: '16 11 * * 1'

env:
  ## LANG: "C" 
  ## LC_CTYPE: "en_US.UTF-8"
  LC_ALL: "C.UTF-8"

jobs:
  ship-war:
    name: Package with JDK ${{ matrix.java }} on ubuntu
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Configure GPG Key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          mkdir -p ~/.gnupg/
          chmod 700 ~/.gnupg
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          chmod 600 ~/.gnupg/*
          gpg --quiet --import ~/.gnupg/private.key
      - name: Create jetty.war
        run: |
          mvn clean package -Dmaven.test.skip=true -Dpmd.skip=true -Pjetty-embed -Prelease${{ matrix.java }}
          gpg2 --clearsign jpsonic-main/target/artifacts-checksums.sha
      - name: Copy README
        # Due to the specifications of actions/upload-artifact@v2.
        # When loading different hierarchies of artifacts, each directory is created.
        run: cp install/keys/README.txt jpsonic-main/target
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: jpsonic-jetty-embedded-for-jdk${{ matrix.java }}-sandbox
          path: |
            jpsonic-main/target/jpsonic.war
            jpsonic-main/target/artifacts-checksums.sha.asc
            jpsonic-main/target/README.txt
          retention-days: 90
  ##########################################################################
  ship-docker-image:
    name: Docker(alpine-amd)
    needs: ship-war
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Get current date
        id: date
        run: echo "current=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: jpsonic-jetty-embedded-for-jdk21-sandbox
      - name: Copy artifact
        run: |
          mkdir -p install/docker/alpine/target/dependency
          mv jpsonic.war install/docker/alpine/target/dependency
      - name: Release with Sandbox Tag
        run: |
          cd install/docker/alpine
          sed -i -e "s/21-jdk-alpine/21-jre-alpine/g" Dockerfile
          sed -i -e "s/EXPOSE 3333/#EXPOSE 3333/g" Dockerfile
          mvn -DdockerTag=sandbox package
          docker import target/docker/jpsonic/jpsonic/tmp/docker-build.tar
          docker buildx build --push --platform linux/amd64,linux/arm64/v8 -t jpsonic/jpsonic:sandbox .
