name: Update Codacy coverage
env:
  JDK_CURRENT: 11.0.9
##########################################################################
on:
  push:
  pull_request:
jobs:
  build:
    name: Update Codacy coverage
    runs-on: ubuntu-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_CURRENT }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Create Jacoco report
        run: mvn -Prelease11 -Punit-test -Psend-coverage -DfailIfNoTests=false -Dpmd.skip=true -Dspotbugs.skip=true -Dcheckstyle.skip=true clean test jacoco:report
      - name: Send Jacoco report
        run: mvn -Psend-coverage com.gavinmogan:codacy-maven-plugin:coverage
